--Crear una tabla
CREATE TABLE EMPLEADOS (
    ID_EMPLEADO NUMBER PRIMARY KEY,
    NOMBRE      VARCHAR2(100),
    SALARIO     NUMBER
);

/*CREAR TABLA CAMPO AUTO INCREMENTABLE
GENERATED ALWAYS AS IDENTITY: No te permite insertar un valor manual en ese campo; Oracle siempre lo controla.
GENERATED BY DEFAULT AS IDENTITY: Te permite insertar un valor propio si lo deseas, pero si lo dejas vacío, Oracle genera el siguiente número.
*/
CREATE TABLE AREAS (
    ID_AREA NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NOMBRE VARCHAR2(100) NOT NULL,
    SOCIEDAD VARCHAR2(50),
    GERENTE VARCHAR(200)
);

--Añadir PK a una tabla ya existente
ALTER TABLE nombre_tabla
ADD CONSTRAINT nombre_pk PRIMARY KEY (columna1, columna2, ...);


--Mostrar estructura de tabla
DESCRIBE EMPLEADOS;

--Agregar una columna
ALTER TABLE EMPLEADOS ADD EMAIL VARCHAR2(150);

--Modificar una columna
ALTER TABLE EMPLEADOS MODIFY
    NOMBRE VARCHAR2(200);

--Renombrar una columna
ALTER TABLE EMPLEADOS RENAME COLUMN NOMBRE TO NOMBRE_COMPLETO;

--Eliminar columna
ALTER TABLE EMPLEADOS DROP COLUMN EMAIL;

--Eliminar tabla
DROP TABLE EMPLEADOS;

--Insertar datos
INSERT INTO EMPLEADOS (ID_EMPLEADO, NOMBRE_COMPLETO)
VALUES (20,'MANUAL ORTEGA');

--HACER UPDATE A ID_EMPLEADO
UPDATE EMPLEADOS SET SALARIO = 3500 WHERE ID_EMPLEADO = 30;


--Agrego FK ID_AREA a una tabla ya existente
ALTER TABLE EMPLEADOS ADD AREA NUMBER;--PRIMERO AÑADO LA COLUMNA

ALTER TABLE EMPLEADOS
    ADD CONSTRAINT FK_AREA_ID_AREA --NOMBRE DE LA RELACIÓN
    FOREIGN KEY ( AREA ) --COLUMNA_HIJO
    REFERENCES AREAS ( ID_AREA ); --COLUMNA_PADRE

--Consulta con JOIN entre dos tablas
--MUESTRA CANTIDAD DE PEDIDOS POR CLIENTE
SELECT CL.NOMBRE,
       COUNT(PE.ID_PEDIDO)
FROM PEDIDOS PE
JOIN CLIENTES CL
ON PE.ID_CLIENTE = CL.ID_CLIENTE
GROUP BY NOMBRE;

--Consulta con JOIN entre tres tablas, agrupamiento, ordenamiento y solo el primer resultado
--MUESTRA CLIENTE CON MÁS PEDIDOS
SELECT CL.NOMBRE, 
       COUNT(PE.ID_PEDIDO) AS TOTAL_PEDIDOS
FROM CLIENTES CL, PEDIDOS PE
WHERE CL.ID_CLIENTE = PE.ID_CLIENTE
GROUP BY CL.ID_CLIENTE, CL.NOMBRE
ORDER BY TOTAL_PEDIDOS DESC;
FETCH FIRST 1 ROWS ONLY;

--Bloque de código PL/SQL para mostrar un mensaje
DECLARE
V_SALUDO VARCHAR2(12):='HOLA, MUNDO!';
BEGIN
    DBMS_OUTPUT.PUT_LINE(V_SALUDO);
END;

--Definición de un procedimiento almacenado
--PROCEDIMIENTO GASTO TOTAL POR CLIENTE
CREATE OR REPLACE PROCEDURE CALCULO_GASTO (P_ID_CLIENTE IN CLIENTES.ID_CLIENTE%TYPE) --argumentos del procedimiento y su tipo de dato
AS
    --definición de variables locales
    V_GASTO_TOTAL NUMBER;
    V_NOMBRE_CLIENTE CLIENTES.NOMBRE%TYPE;
BEGIN
    --Consulta para calcular el gasto total del cliente ingresado
    SELECT cl.nombre, SUM(p.precio * pe.cantidad)
    INTO V_NOMBRE_CLIENTE, V_GASTO_TOTAL
    FROM pedidos pe
    JOIN productos p
    ON pe.id_producto = p.id_producto
    JOIN clientes cl
    on pe.id_cliente = cl.id_cliente
    WHERE pe.id_cliente = P_ID_CLIENTE
    GROUP BY cl.nombre;
 
    
    DBMS_OUTPUT.PUT_LINE('El cliente ' || V_NOMBRE_CLIENTE || ' gastó: $' || V_GASTO_TOTAL);
 
    --Excepción en caso de no existir el P_ID_CLIENTE ingresado
    EXCEPTION
        WHEN
            NO_DATA_FOUND
        THEN
            DBMS_OUTPUT.PUT_LINE('Error: No se encontró un cliente con el ID ' || P_ID_CLIENTE);
END;
 
--Llamada del procedimiento
BEGIN
    CALCULO_GASTO(1);
END;

--Definición de una función
--FUNCIÓN GASTO TOTAL POR CLIENTE
CREATE OR REPLACE FUNCTION F_CALCULO_GASTO(P_ID_CLIENTE IN CLIENTES.ID_CLIENTE%TYPE) --argumentos de la función y su tipo de dato
--tipo de dato que va a retornar la función 
RETURN NUMBER
--definición de variables locales
IS 
 V_GASTO_TOTAL NUMBER;
--consulta para calcular el gasto total del cliente ingresado
BEGIN
    SELECT SUM(p.precio * pe.cantidad)
    INTO V_GASTO_TOTAL
    FROM pedidos pe
    JOIN productos p
    ON pe.id_producto = p.id_producto
    WHERE pe.id_cliente = P_ID_CLIENTE;
    
    --retorna el valor del gasto total calculado
    RETURN V_GASTO_TOTAL;
 
END F_CALCULO_GASTO; --nombre de la función para hacer más legible el código
--indica que el END corresponde a la función F_CALCULO_GASTO


--Llamada de una función y mostrar su resultado
DECLARE
    v_resultado NUMBER;
BEGIN
    v_resultado := F_CALCULO_GASTO(1); --asigna el valor que retorna la funcion a la variable v_resultado
    DBMS_OUTPUT.PUT_LINE('El resultado es: ' || v_resultado); --imprime el resutado
END;

--Crea una secuencia
CREATE SEQUENCE nombre_secuencia
  START WITH 1        -- valor inicial
  INCREMENT BY 1      -- cuánto aumenta cada vez
  NOCACHE             -- opcional, evita reservar valores en memoria
  NOCYCLE;            -- opcional, evita que se reinicie al llegar al máximo


--Modifica una primary key para asignarle el valor de una secuencia
ALTER TABLE PEDIDOS MODIFY ID_PEDIDO NUMBER DEFAULT SEQ_PEDIDOS.NEXTVAL;

--Vacía una tabla
TRUNCATE TABLE PEDIDOS;
